knp_snappy:
    pdf:
        enabled:    true
        binary: '"C:/Program Files/wkhtmltopdf/bin/wkhtmltopdf.exe"'
        options: []
            # lowquality: true
            # page-size: A4
    image:
        enabled:    true
        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
